pipelines:
  custom:
    customPipelineWithRunnerStep:
      - step:
          name: Step 1
          runs-on: self.hosted 
          script:
            - echo "This step will run on a self hosted runner with 128 GB of memory.";
      - step:
          name: Step 2
          script:
            - echo "This step will run on Atlassian's infrastructure as usual.";
