pipelines:
  custom:
    customPipelineWithRunnerStep:
      - step:
          name: Step 1
          runs-on: 
            - 'self.hosted'
            - 'api.club7.com.br'
          script:
            - echo "This step will run on a self hosted runner with 128 GB of memory.";
      - step:
          name: Step 2
          script:
            - echo "This step will run on Atlassian's infrastructure as usual.";
