# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install and Build
      run: | 
        npm install
        npm run build
     
  Development:
    runs-on: ubuntu-latest
    needs: [ build ]

    environment: homolog

    steps:
      
      - name: Send Files to Server
        uses: appleboy/ssh-action@master
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          
        with:
          host: 143.244.162.174
          username: deploy-api
          key: $SSH_KEY
          port: 22
          source: "./*"
          target: "teste"
          fingerprint: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVDtq81U1so8h0msaSt0bpMlAonoTBs/NN8FYU6LRbsI3FpIObXX6zSguStkaVZqfLxX9lhODCB00KDFwXjAO8MJIiSo6lcwfYKuIlheXl+213+7vyuMKXTFtQkpYevXpE5JREdhJdfIrdb2Z92pBNZxGTR8vEFEQUSmLxH7gIEtFtJvuSKORfU2MUfOk5Iw9sQLHFwriuS8BxObHonVFLIimVj9swOS5arDjujCgOfebHRCHvua3vR7z7kCso9wPEts6I9mzNSYuqmHvMEoZCYaZvu93yib55XJpAm74XjP2eyKBv6fqn6Vawmzw9BzMpgYKosdMhnbUQnEwh5lfRVf0OSua/pXsCixNHLFSSIdn7IDB3B7rsH3cmE3BlnwMnsMHCjWd6iBQWywqbdhqsI7NGKsRi1LyxKULJwLvVlH2/oMKL9fvo/VmBOWwCOA/7sblZSg1QcBhhTphpmTRlMA3uBKXXugeEMVri/tP+I+vZp6PQ3J1ybEMOmBmVKAs= rafael coelho@LAPTOP-BQOEBN6J

          


      
