# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install and Build
      run: | 
        npm install
        npm run build
     
  Development:
    runs-on: ubuntu-latest
    needs: [ build ]

    environment: homolog

    steps:
      
      - name: Send Files to Server
        uses: appleboy/ssh-action@master
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          
        with:
          host: 143.244.162.174
          username: deploy-api
#           key: $SSH_KEY
          port: 22
          source: "./*"
          target: "teste"
          fingerprint: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDpE2dYLzMQb4j8n7LG9t92M/5rodVbpYAKUTlXY436J0/iN0dUkBOZ/C/BBlR9rF2BJBhoes7DhD3yzVju0zVr4+ZjKd3FEzeqZ7XlRIh+qdN+c2uWj2rMG5PPJ9bIeYRiSaUf2HVfuGDxEXZFof+ZCeInNo3H7DSYRm9y3sG+F5WM2VYK0DjeM/zVgmPf9V1vicH1E+4FGURZ1FWT1joRHzQ8DIykX1EPNHKnFnjy9TZ+/x181ir86efY4NCrSpSHGZ8yBsnlPeWyWdrlK2kqaKMw0qO77xiXWcISF2/LQ9UUxpQ9OsI3y5UuS7uNO5OfkifqNsokmWgL/aT6BsZoW89/f/fwvmdPGgrRldDc2Z8B4yu/c20/DioER261BfMKxYotz9ZVu7HWIGqETTJ66TdWUrz39wrCt+seIUoCXUjnc9NU5k3KbjQDQe0qaz/LhydidU/5ypjZKEsE82ejs8Mb2CfKg2po8bH0giLRNkmZNjiWjCAuxAJQk+tMlVE= deploy-api@deploy

          


      
