# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install and Build
      run: | 
        npm install
        npm run build

    - name: Define Environment Variables
      env: # Ou como uma variável de ambiente
        MAIL_FROM: ${{ secrets.MAIL_FROM }}
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USER: ${{ secrets.MAIL_USER }}
      run: |
        cp .env.example .env
        sed "s/@@MAIL_FROM/$MAIL_FROM/g" -i .env
        sed "s/@@MAIL_HOST/$MAIL_HOST/g" -i .env
        sed "s/@@MAIL_PASS/$MAIL_PASS/g" -i .env
        sed "s/@@MAIL_PORT/$MAIL_PORT/g" -i .env
        sed "s/@@MAIL_USER/$MAIL_USER/g" -i .env
       
    - name: Start PM2
      run: pm2 start dist/index.js --name club7-api -f
        
      
